### ISSUE TITLE
Making this project more readable and understandable

### ISSUE THREAD

**Issue by ADeathPleaseB** [SpiritXIV/Chrome-Hidden-Files#2]
Files named "naenae" don't really clarify what it does, and many of these files seem redundant and aren't needed at all.

**Comment by SpiritXIV** [comment]
its for a future update I want to do,

**Comment by SpiritXIV** [comment]
> Files named "naenae" don't really clarify what it does, and many of these files seem redundant and aren't needed at all.

It is not apart of the main website for one reason, and that is because it crashes your computer when you go to it, so I see no need to add it to the website, just to get your computer frozen. And I'm being flat out honest to you, I know the code is messy, I want to clean it up for a future update, and tho extra files are used as references for me when I want to do something. You made a fork, now if you want to change it, you can. Just stop putting issues that don't make sense or don't belong, If a file doesn't clarify what it is, then it shouldn't matter to you, you're not the one who started this website.
